name: Build and Push Docker Image
 
on:
  push:
    branches: ["main"]
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-product-app 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'temurin'
 
      - name: Build JAR
        run: mvn -q -DskipTests clean package
 
      - name: Login to dockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
      - name: Build Docker Image (latest + sha)
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
        
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-product-app:latest
